version: '3'
services:
  misp:
    depends_on:
      - db
      - redis
    image: ghcr.io/legoguy1000/misp:2.4.165
    build:
      context: misp
      dockerfile: ./Dockerfile
      args:
        MISP_VERSION: 2.4.165
    # entrypoint: sleep 5h
    restart: unless-stopped
    ports:
      - "9090:8080"
    volumes:
      - /dev/urandom:/dev/random
      # - ./config/test.php:/tmp/config.external.php:ro
    # entrypoint: /bin/bash -c "sleep 5h"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=misp
      - MYSQL_USER=misp
      - MYSQL_PASSWORD=pAyRGUTvaqx?7!gd5Yr#
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - MISP_MODULES_URL=misp_modules
      # - MISP_MODULES_PORT=6666
      - ADMIN_PASS=1qaz@WSX1qaz@WSX
      # - EXTERNAL_CONFIG=/tmp/config.external.php
      # - EXTERNAL_BOOTSRAP=/tmp/config.external.php
      # - SETTING_Plugin_Enrichment_geoip_country_enabled=true
      # - SETTING_Plugin_Enrichment_geoip_country_local_geolite_db=/misp_modules/geoip/GeoLite2-Country.mmdb
      # - SETTING_Plugin_Enrichment_geoip_city_enabled=true
      # - SETTING_Plugin_Enrichment_geoip_city_local_geolite_db=/misp_modules/geoip/GeoLite2-City.mmdb
      # - SETTING_Plugin_Enrichment_geoip_asn_enabled=true
      # - SETTING_Plugin_Enrichment_geoip_asn_local_geolite_db=/misp_modules/geoip/GeoLite2-ASN.mmdb
      # - SETTING_Plugin_CustomAuth_custom_password_reset=https://google.com
      # - SETTING_Plugin_CustomAuth_custom_logout=https://google.com
      - SETTING_MISP_host_org_id=1
      - SETTING_MISP_language=eng
      - SETTING_MISP_org=TEST
      - SETTING_MISP_baseurl=http://localhost:9090
      - SETTING_MISP_external_baseurl=http://localhost:9090
      - SETTING_Security_advanced_authkeys=true
      - SETTING_Security_csp_enforce=true
      - SETTING_Plugin_Enrichment_hover_popover_only=false
      - SETTING_Security_disable_browser_cache=true
      - SETTING_Security_check_sec_fetch_site_header=true
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=misp
      - MYSQL_USER=misp
      - MYSQL_PASSWORD=pAyRGUTvaqx?7!gd5Yr#
      - MYSQL_ROOT_PASSWORD=*7Adrq^a8D5&ALtbcwM?
  redis:
    image: "redis:latest"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
  # misp_modules:
  #   image: misp-modules:2.4.157
  #   build:
  #     context: misp-modules
  #     dockerfile: ./Dockerfile
  #     args:
  #       MISP_MODULES_VERSION: 2.4.157
  #       MAXMIND_API_KEY:
  #   restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  #   stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
