name: Build container images
on:
  push:
    branches:
      - '*'
      - '!main'
env:
  MISP_VERSION: 2.4.165
  MISP_MODULES_VERSION: 2.4.165
jobs:
  build-misp:
    name: Build MISP Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: "./misp"
          push: false
          build-args: |
            MISP_VERSION=${{ env.MISP_VERSION }}
  build-misp-modules:
    name: Build MISP Modules Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: "./misp-modules"
          push: false
          build-args: |
            MAXMIND_API_KEY=${{ secrets.MAXMIND_API_KEY }}
            MISP_MODULES_VERSION=${{ env.MISP_MODULES_VERSION }}
