name: Build and Publish container images
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  MISP_VERSION: 2.4.161
  MISP_MODULES_VERSION: 2.4.160
permissions:
  packages: write
  contents: read
jobs:
  build-misp:
    name: Build MISP Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: "./misp"
          push: true
          tags: ${{ env.REGISTRY }}/legoguy1000/misp:${{ env.MISP_VERSION }}
          build-args: |
            MISP_VERSION=${{ env.MISP_VERSION }}
  build-misp-modules:
    name: Build MISP Modules Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: "./misp-modules"
          push: true
          tags: ${{ env.REGISTRY }}/legoguy1000/misp-modules:${{ env.MISP_MODULES_VERSION }}
          build-args: |
            MAXMIND_API_KEY=${{ secrets.MAXMIND_API_KEY }}
            MISP_MODULES_VERSION=${{ env.MISP_MODULES_VERSION }}
