name: Build and Publish container images
on:
  release:
    types: [published]
env:
  REGISTRY: ghcr.io
jobs:
  build-misp:
    name: Build MISP Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: "./misp"
          push: true
          tags: ${{ env.REGISTRY }}/legoguy1000/misp:${{ github.event.release.tag_name }}
  build-misp-modules:
    name: Build MISP Modules Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: "./misp-modules"
          push: true
          tags: ${{ env.REGISTRY }}/legoguy1000/misp-modules:${{ github.event.release.tag_name }}
          build-args: |
            MAXMIND_API_KEY=${{ secrets.MAXMIND_API_KEY }}